// GENERATED by scripts/gen-templates.ts — do not edit.
// Edit the real files under templates/ and run `deno task gen`.

export const CORE_VERSION = "^0.0.5";

export interface TemplateFile {
  path: string;
  contents: string;
}

const FILES: TemplateFile[] = [
  {
    path: "deno.json",
    contents:
      '{\n  "tasks": {\n    "dev": "vite",\n    "build": "vite build && vite build --ssr app/server.ts",\n    "preview": "vite preview",\n    "start": "deno serve -A server.prod.ts",\n    "check": "deno fmt --check . && deno lint . && deno check"\n  },\n  "imports": {\n    "chevalier": "jsr:@chevalier/core@{{CORE}}",\n    "chevalier/client": "jsr:@chevalier/core@{{CORE}}/client",\n    "chevalier/registry": "jsr:@chevalier/core@{{CORE}}/registry",\n    "chevalier/static": "jsr:@chevalier/core@{{CORE}}/static",\n    "chevalier/vite": "jsr:@chevalier/core@{{CORE}}/vite",\n    "hono": "npm:hono@^4.6.0",\n    "preact": "npm:preact@^10.24.0",\n    "preact/": "npm:/preact@^10.24.0/",\n    "preact-render-to-string": "npm:preact-render-to-string@^6.5.0",\n    "vite": "npm:vite@^8.0.0",\n    "@deno/vite-plugin": "npm:@deno/vite-plugin@^2.0.2",\n    "@prefresh/vite": "npm:@prefresh/vite@^2.4.0",\n    "@prefresh/core": "npm:@prefresh/core@^1.5.0",\n    "@prefresh/utils": "npm:@prefresh/utils@^1.2.0"\n  },\n  "nodeModulesDir": "auto",\n  "exclude": ["dist"],\n  "compilerOptions": {\n    "jsx": "react-jsx",\n    "jsxImportSource": "preact",\n    "lib": ["dom", "dom.iterable", "deno.ns", "esnext"],\n    "types": ["vite/client"]\n  }\n}\n',
  },
  {
    path: "vite.config.ts",
    contents:
      'import { defineConfig } from "vite";\nimport { chevalierConfig } from "chevalier/vite";\n\n// Pass { appRoot, entry } to override the ./app + /app/server.ts defaults.\nexport default defineConfig(chevalierConfig());\n',
  },
  {
    path: "server.prod.ts",
    contents:
      '// Production entry: `deno task start` after `deno task build`.\n// The SSR bundle only exports a Hono app; export a { fetch } handler so\n// `deno serve` provides the listener (the Deno Deploy-portable form). Static\n// files live under dist/client: hashed chunks in /assets/ (immutable) plus\n// public/ files copied to the root (favicon etc., revalidated). Anything not on\n// disk falls through to the app\'s SSR routes. A CDN in front is still\n// recommended for high traffic. See the README\'s Deploy section.\nimport app from "./dist/server/server.mjs";\nimport { serveStatic } from "chevalier/static";\n\nconst CLIENT_DIR = new URL("./dist/client", import.meta.url).pathname;\n// Content-hashed names ⇒ safe to pin forever. Public files keep stable names,\n// so they must revalidate or a favicon swap never propagates.\nconst IMMUTABLE = "public, max-age=31536000, immutable";\nconst REVALIDATE = "public, no-cache";\n\nexport default {\n  fetch: serveStatic({\n    fsRoot: CLIENT_DIR,\n    fallthrough: (req) => app.fetch(req),\n    cacheControl: (pathname) =>\n      pathname.startsWith("/assets/") ? IMMUTABLE : REVALIDATE,\n  }),\n};\n',
  },
  {
    path: ".gitignore",
    contents:
      "node_modules/\n.deno/\ndist/\n.vite/\ndeno.lock\n.DS_Store\n*.log\n",
  },
  {
    path: "README.md",
    contents:
      "# {{NAME}}\n\nA [Chevalier](https://jsr.io/@chevalier/core) app.\n\n```sh\ndeno install\ndeno task dev       # start the dev server\ndeno task check     # format, lint, and type-check\n```\n\nRoutes live in `app/routes/`, islands in `app/islands/`. Static files (favicon,\nrobots.txt, images) go in `public/` and are served from the site root.\n\n## Production\n\n```sh\ndeno task build     # build the app\ndeno task start     # serve the build\n```\n\nServes on port 8000. To change it, run `deno serve` directly with `--port`\nbefore the entry: `deno serve -A --port 3000 server.prod.ts`.\n\n## Deploy to Deno Deploy\n\nBuild first, then ship `dist/` — it's gitignored, so include it explicitly:\n\n```sh\ndeno task build\ndeno install -Arf jsr:@deno/deployctl\ndeployctl deploy --include=dist --include=deno.json --entrypoint=server.prod.ts\n```\n",
  },
  {
    path: "public/favicon.svg",
    contents:
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">\n  <rect width="32" height="32" rx="6" fill="#111827" />\n  <path\n    d="M16 7l7 4v10l-7 4-7-4V11z"\n    fill="none"\n    stroke="#f59e0b"\n    stroke-width="2"\n    stroke-linejoin="round"\n  />\n</svg>\n',
  },
  {
    path: "app/server.ts",
    contents:
      '// SSR entry. Globs routes + the convention pages and hands them to defineApp,\n// which owns manifest, island-URL, and CSP wiring.\n// vite/client augments ImportMeta with glob/env, which Deno doesn\'t know.\n/// <reference types="vite/client" />\n\nimport { defineApp } from "chevalier";\nimport type { RouteModule } from "chevalier";\nimport { urls as devIslandUrls } from "virtual:chevalier-islands";\nimport { manifest } from "virtual:chevalier-manifest";\nimport Layout from "./routes/_layout.tsx";\nimport NotFound from "./routes/_404.tsx";\nimport ErrorPage from "./routes/_error.tsx";\n\nexport default defineApp({\n  routes: import.meta.glob<RouteModule>(\n    "/app/routes/**/*.{tsx,jsx,ts}",\n    { eager: false },\n  ) as Record<string, () => Promise<RouteModule>>,\n  devIslandUrls,\n  manifest,\n  layout: Layout,\n  notFound: NotFound,\n  error: ErrorPage,\n});\n',
  },
  {
    path: "app/chevalier-islands.d.ts",
    contents:
      '// Editor-only types; the real module is generated by the chevalier Vite plugin.\ndeclare module "virtual:chevalier-islands" {\n  export const urls: Record<string, string>;\n}\n',
  },
  {
    path: "app/chevalier-manifest.d.ts",
    contents:
      '// Editor-only types; the real module is generated by the chevalier Vite plugin.\ndeclare module "virtual:chevalier-manifest" {\n  import type { ViteManifest } from "chevalier";\n  export const manifest: ViteManifest | undefined;\n}\n',
  },
  {
    path: "app/routes/_layout.tsx",
    contents:
      'import type { LayoutProps } from "chevalier";\n\n// `boot` is "" for a page with no islands, shipping zero client JS.\nexport default function Layout(\n  { childrenHtml, boot = "", nonce }: LayoutProps,\n) {\n  return (\n    <html lang="en">\n      <head>\n        <meta charSet="utf-8" />\n        <meta name="viewport" content="width=device-width, initial-scale=1" />\n        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />\n        <title>Chevalier app</title>\n      </head>\n      <body>\n        <nav>\n          <a href="/">home</a> · <a href="/about">about</a>\n        </nav>\n        <main\n          id="chevalier-root"\n          dangerouslySetInnerHTML={{ __html: childrenHtml }}\n        />\n        {boot\n          ? (\n            <script\n              type="module"\n              nonce={nonce}\n              dangerouslySetInnerHTML={{ __html: boot }}\n            />\n          )\n          : null}\n      </body>\n    </html>\n  );\n}\n',
  },
  {
    path: "app/routes/_404.tsx",
    contents:
      '// Rendered for any unmatched route (status 404). Wired via defineApp({ notFound }).\nexport default function NotFound() {\n  return (\n    <div>\n      <h1>404 — Not found</h1>\n      <p>\n        Nothing here. <a href="/">Go home</a>.\n      </p>\n    </div>\n  );\n}\n',
  },
  {
    path: "app/routes/_error.tsx",
    contents:
      '// Rendered when a route throws (status 500). Wired via defineApp({ error }).\nexport default function ErrorPage({ error }: { error: unknown }) {\n  const message = error instanceof Error ? error.message : String(error);\n  return (\n    <div>\n      <h1>500 — Something went wrong</h1>\n      <p>{message}</p>\n      <p>\n        <a href="/">Go home</a>.\n      </p>\n    </div>\n  );\n}\n',
  },
  {
    path: "app/routes/index.tsx",
    contents:
      'import Counter from "../islands/counter.tsx";\nimport Quote from "../islands/quote.tsx";\n\nexport default function Home() {\n  return (\n    <div>\n      <h1>Chevalier</h1>\n      <p>A file-routed Deno meta-framework that ships islands, not bundles.</p>\n      <Counter start={3} />\n      <h2>Fetch — click to load fake data from /api/quote</h2>\n      <Quote />\n    </div>\n  );\n}\n',
  },
  {
    path: "app/routes/about.tsx",
    contents:
      "export default function About() {\n  return (\n    <div>\n      <h1>About</h1>\n      <p>\n        This page is fully server-rendered static HTML — no island, no client JS\n        for its content. Edit this file in dev to see a full page reload.\n      </p>\n    </div>\n  );\n}\n",
  },
  {
    path: "app/routes/hello/[name].tsx",
    contents:
      '// Dynamic-param page with a loader: /hello/ada → props { params, greeting }.\nimport type { PageLoader } from "chevalier";\n\nexport const loader: PageLoader = (c) => {\n  const name = c.req.param("name");\n  return { greeting: `Hello, ${name}!`, at: new Date().toISOString() };\n};\n\nexport default function Hello(\n  props: { params: { name: string }; greeting: string; at: string },\n) {\n  return (\n    <div>\n      <h1>{props.greeting}</h1>\n      <p>\n        Rendered server-side at {props.at} for param{" "}\n        <code>{props.params.name}</code> — no client JS.\n      </p>\n    </div>\n  );\n}\n',
  },
  {
    path: "app/routes/api.ts",
    contents:
      '// Handler route (export const app) → mounted at /api, serving any HTTP method.\n// Routes are file-relative: "/" is /api, "/echo" is /api/echo.\nimport { Hono } from "hono";\n\nconst QUOTES = [\n  "Ship it.",\n  "It works on my machine.",\n  "Islands all the way down.",\n  "Zero JS until you need it.",\n];\n\nexport const app = new Hono()\n  .get("/", (c) => c.json({ ok: true, route: "/api" }))\n  .post("/echo", async (c) => c.json({ echo: await c.req.json() }))\n  // Fake data endpoint the Quote island fetches on click. GET /api/quote.\n  .get(\n    "/quote",\n    (c) => c.json({ quote: QUOTES[Math.floor(Math.random() * QUOTES.length)] }),\n  );\n',
  },
  {
    path: "app/islands/counter.tsx",
    contents:
      '// Island (under islands/). Interactive on the client after hydration.\nimport { useState } from "preact/hooks";\n\nexport default function Counter({ start = 0 }: { start?: number }) {\n  const [n, setN] = useState(start);\n  return (\n    <button type="button" onClick={() => setN((v) => v + 1)}>\n      counts: {n}\n    </button>\n  );\n}\n',
  },
  {
    path: "app/islands/quote.tsx",
    contents:
      '// Island: fetches fake data from the /api/quote handler on click.\n\nimport { useState } from "preact/hooks";\n\nexport default function Quote() {\n  const [quote, setQuote] = useState<string | null>(null);\n  const [loading, setLoading] = useState(false);\n\n  async function fetchQuote() {\n    setLoading(true);\n    try {\n      const res = await fetch("/api/quote");\n      const data = await res.json();\n      setQuote(data.quote);\n    } finally {\n      setLoading(false);\n    }\n  }\n\n  return (\n    <div>\n      <button type="button" onClick={fetchQuote} disabled={loading}>\n        {loading ? "loading…" : "get a quote"}\n      </button>\n      {quote ? <p>“{quote}”</p> : null}\n    </div>\n  );\n}\n',
  },
];

/** All files for a fresh app, with {{CORE}}/{{NAME}} substituted. */
export function templateFiles(projectName: string): TemplateFile[] {
  const sub = (s: string) =>
    s.replaceAll("{{CORE}}", CORE_VERSION).replaceAll("{{NAME}}", projectName);
  return FILES.map((f) => ({ path: f.path, contents: sub(f.contents) }));
}
