// Files a fresh Chevalier app is scaffolded from. Kept in sync with
// examples/basic; that example is the reference for the real framework wiring.
// {{CORE}} is replaced with the pinned @chevalier/core version spec at write time.

export const CORE_VERSION = "^0.0.3";

export interface TemplateFile {
  path: string;
  contents: string;
}

const denoJson = `{
  "tasks": {
    "dev": "vite",
    "build": "vite build && vite build --ssr app/server.ts",
    "preview": "vite preview"
  },
  "imports": {
    "chevalier": "jsr:@chevalier/core@{{CORE}}",
    "chevalier/client": "jsr:@chevalier/core@{{CORE}}/client",
    "chevalier/registry": "jsr:@chevalier/core@{{CORE}}/registry",
    "hono": "npm:hono@^4.6.0",
    "preact": "npm:preact@^10.24.0",
    "preact/": "npm:/preact@^10.24.0/",
    "preact-render-to-string": "npm:preact-render-to-string@^6.5.0",
    "vite": "npm:vite@^7.0.0",
    "@deno/vite-plugin": "npm:@deno/vite-plugin@^2.0.2",
    "@prefresh/vite": "npm:@prefresh/vite@^2.4.0",
    "@prefresh/core": "npm:@prefresh/core@^1.5.0",
    "@prefresh/utils": "npm:@prefresh/utils@^1.2.0"
  },
  "nodeModulesDir": "auto",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    "lib": ["dom", "dom.iterable", "deno.ns", "esnext"]
  }
}
`;

const viteConfig = `import { defineConfig } from "vite";
import deno from "@deno/vite-plugin";
import { chevalier } from "chevalier";

// @deno/vite-plugin resolves jsr:/npm: specifiers via Deno's loader; its hooks
// only engage on Vite 7 (Environment API). Client/SSR need separate outDirs.
export default defineConfig(({ isSsrBuild }) => ({
  // One Preact instance across SSR + islands is required for hydration.
  resolve: {
    dedupe: ["preact", "preact/hooks", "preact-render-to-string", "hono"],
  },
  optimizeDeps: { noDiscovery: true, include: [] },
  // chevalier before deno so it claims virtual:chevalier-islands before the
  // deno loader rejects the virtual: scheme.
  plugins: [chevalier({ appRoot: "./app", entry: "/app/server.ts" }), deno()],
  build: isSsrBuild
    ? { outDir: "dist/server" }
    : {
      // Client entry + island inputs are injected by the chevalier plugin.
      outDir: "dist/client",
      manifest: true,
    },
}));
`;

const server =
  `// SSR entry. Globs routes + the layout override, then hands them to createApp.
// vite/client augments ImportMeta with glob/env, which Deno doesn't know.
/// <reference types="vite/client" />

import { Hono } from "hono";
import { NONCE, secureHeaders } from "hono/secure-headers";
import { createApp, resolveIslandUrls } from "chevalier";
import type { RouteModule, ViteManifest } from "chevalier";
import { urls as devIslandUrls } from "virtual:chevalier-islands";
import Layout from "./routes/_layout.tsx";
import NotFound from "./routes/_404.tsx";
import ErrorPage from "./routes/_error.tsx";

const routes = import.meta.glob<RouteModule>(
  "/app/routes/**/*.{tsx,jsx,ts}",
  { eager: false },
) as Record<string, () => Promise<RouteModule>>;

// Eager + PROD-guarded so the manifest is inlined at build time only.
const manifest = import.meta.env.PROD
  ? (Object.values(
    import.meta.glob<{ default: ViteManifest }>(
      "/dist/client/.vite/manifest.json",
      { eager: true },
    ),
  )[0]?.default)
  : undefined;

const base = new Hono();
if (import.meta.env.PROD) {
  base.use("*", secureHeaders({ contentSecurityPolicy: { scriptSrc: [NONCE] } }));
}

const app = createApp({
  app: base,
  routes,
  layout: Layout,
  notFound: NotFound,
  error: ErrorPage,
  manifest,
  islandUrls: resolveIslandUrls(devIslandUrls, manifest),
});

export default app;
`;

const islandsDts =
  `// Editor-only types; the real module is generated by the chevalier Vite plugin.
declare module "virtual:chevalier-islands" {
  export const urls: Record<string, string>;
}
`;

const layout = `import type { LayoutProps } from "chevalier";

// \`boot\` is "" for a page with no islands, shipping zero client JS.
export default function Layout({ childrenHtml, boot = "", nonce }: LayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Chevalier app</title>
      </head>
      <body>
        <nav>
          <a href="/">home</a> · <a href="/about">about</a>
        </nav>
        <main
          id="chevalier-root"
          dangerouslySetInnerHTML={{ __html: childrenHtml }}
        />
        {boot
          ? (
            <script
              type="module"
              nonce={nonce}
              dangerouslySetInnerHTML={{ __html: boot }}
            />
          )
          : null}
      </body>
    </html>
  );
}
`;

const index = `import Counter from "../islands/counter.tsx";

export default function Home() {
  return (
    <div>
      <h1>Chevalier</h1>
      <p>A file-routed Deno meta-framework that ships islands, not bundles.</p>
      <Counter start={3} />
    </div>
  );
}
`;

const about = `export default function About() {
  return (
    <div>
      <h1>About</h1>
      <p>
        This page is fully server-rendered static HTML — no island, no client JS
        for its content. Edit this file in dev to see a full page reload.
      </p>
    </div>
  );
}
`;

const notFound =
  `// Rendered for any unmatched route (status 404). Wired via createApp({ notFound }).
export default function NotFound() {
  return (
    <div>
      <h1>404 — Not found</h1>
      <p>
        Nothing here. <a href="/">Go home</a>.
      </p>
    </div>
  );
}
`;

const errorPage =
  `// Rendered when a route throws (status 500). Wired via createApp({ error }).
export default function ErrorPage({ error }: { error: unknown }) {
  const message = error instanceof Error ? error.message : String(error);
  return (
    <div>
      <h1>500 — Something went wrong</h1>
      <p>{message}</p>
      <p>
        <a href="/">Go home</a>.
      </p>
    </div>
  );
}
`;

const api =
  `// Handler route (export const app) → mounted at /api, serving any HTTP method.
// Routes are file-relative: "/" is /api, "/echo" is /api/echo.
import { Hono } from "hono";

export const app = new Hono()
  .get("/", (c) => c.json({ ok: true, route: "/api" }))
  .post("/echo", async (c) => c.json({ echo: await c.req.json() }));
`;

const counter =
  `// Island (under islands/). Interactive on the client after hydration.
import { useState } from "preact/hooks";

export default function Counter({ start = 0 }: { start?: number }) {
  const [n, setN] = useState(start);
  return (
    <button type="button" onClick={() => setN((v) => v + 1)}>
      counts: {n}
    </button>
  );
}
`;

const gitignore = `node_modules/
.deno/
dist/
.vite/
deno.lock
.DS_Store
*.log
`;

const readme = (name: string) =>
  `# ${name}

A [Chevalier](https://jsr.io/@chevalier/core) app.

\`\`\`sh
deno install
deno task dev       # vite dev server
deno task build     # client + SSR build
deno task preview   # preview the build
\`\`\`

Routes live in \`app/routes/\`, islands in \`app/islands/\`. A page with no
islands ships zero client JavaScript.
`;

/** All files for a fresh app, with {{CORE}} substituted. */
export function templateFiles(projectName: string): TemplateFile[] {
  const sub = (s: string) => s.replaceAll("{{CORE}}", CORE_VERSION);
  return [
    { path: "deno.json", contents: sub(denoJson) },
    { path: "vite.config.ts", contents: viteConfig },
    { path: ".gitignore", contents: gitignore },
    { path: "README.md", contents: readme(projectName) },
    { path: "app/server.ts", contents: server },
    { path: "app/chevalier-islands.d.ts", contents: islandsDts },
    { path: "app/routes/_layout.tsx", contents: layout },
    { path: "app/routes/_404.tsx", contents: notFound },
    { path: "app/routes/_error.tsx", contents: errorPage },
    { path: "app/routes/index.tsx", contents: index },
    { path: "app/routes/about.tsx", contents: about },
    { path: "app/routes/api.ts", contents: api },
    { path: "app/islands/counter.tsx", contents: counter },
  ];
}
