// Editor-only types; the real module is generated by the chevalier Vite plugin.
declare module "virtual:chevalier-manifest" {
  import type { ViteManifest } from "chevalier";
  export const manifest: ViteManifest | undefined;
}
