// Inlines init/templates/ into committed templates.gen.ts so the published
// scaffolder reads nothing at runtime — no fetch of JSR package data files (the
// Fresh scaffolder makes the same embed-not-fetch choice). Run via deno task gen.

import { encodeBase64 } from "@std/encoding/base64";

const HERE = new URL("../", import.meta.url);
const TEMPLATES = new URL("templates/", HERE);
const OUT = new URL("templates.gen.ts", HERE);

// [source, outputPath, binary?]. Source names diverge from output where a
// literal name breaks tooling: `gitignore` avoids a real dotfile; `deno.json`
// stays literal but is unpublished so Deno never loads it as a config for this
// dir. binary marks files that can't survive {{CORE}}/{{NAME}} substitution.
// deno.json takes no comments (smoke.ts JSON.parses it), so note here: its
// `exclude` serves fmt and lint only — check follows imports past any exclude.
const MANIFEST: ReadonlyArray<readonly [string, string, boolean?]> = [
  ["deno.json", "deno.json"],
  ["vite.config.ts", "vite.config.ts"],
  ["server.prod.ts", "server.prod.ts"],
  ["gitignore", ".gitignore"],
  ["README.md", "README.md"],
  ["public/favicon.png", "public/favicon.png", true],
  ["app/routes/_app.tsx", "app/routes/_app.tsx"],
  ["app/routes/_layout.tsx", "app/routes/_layout.tsx"],
  ["app/routes/_404.tsx", "app/routes/_404.tsx"],
  ["app/routes/_error.tsx", "app/routes/_error.tsx"],
  ["app/routes/index.tsx", "app/routes/index.tsx"],
  ["app/routes/about.tsx", "app/routes/about.tsx"],
  ["app/routes/hello/[name].tsx", "app/routes/hello/[name].tsx"],
  ["app/routes/guestbook.tsx", "app/routes/guestbook.tsx"],
  ["app/routes/login.tsx", "app/routes/login.tsx"],
  ["app/routes/admin/index.tsx", "app/routes/admin/index.tsx"],
  ["app/routes/admin/_middleware.ts", "app/routes/admin/_middleware.ts"],
  ["app/routes/api.ts", "app/routes/api.ts"],
  ["app/styles.css", "app/styles.css"],
  ["app/islands/counter.tsx", "app/islands/counter.tsx"],
  ["app/islands/quote.tsx", "app/islands/quote.tsx"],
];

// JSON.stringify escapes any bytes (backticks, ${}, backslashes) — no
// hand-managed template escapes, which is what the old inline templates.ts had.
function jsString(s: string): string {
  return JSON.stringify(s);
}

// Every source path under templates/, forward-slash, templates-root-relative.
async function walkTemplates(dir = TEMPLATES, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  for await (const e of Deno.readDir(dir)) {
    if (e.name === ".DS_Store") continue;
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.isDirectory) {
      out.push(...await walkTemplates(new URL(`${e.name}/`, dir), rel));
    } else {
      out.push(rel);
    }
  }
  return out;
}

// MANIFEST is hand-listed, so an unlisted file silently never ships (the /admin 404).
async function assertManifestCovers(): Promise<void> {
  const listed = new Set(MANIFEST.map(([source]) => source));
  const missing = (await walkTemplates()).filter((f) => !listed.has(f)).sort();
  if (missing.length) {
    console.error(
      "MANIFEST is missing files under templates/:\n" +
        missing.map((f) => `  - ${f}`).join("\n") +
        "\nAdd them to MANIFEST in scripts/gen-templates.ts.",
    );
    Deno.exit(1);
  }
}

async function render(): Promise<string> {
  const entries: string[] = [];
  for (const [source, path, binary] of MANIFEST) {
    const url = new URL(source, TEMPLATES);
    if (binary) {
      const bytes = await Deno.readFile(url);
      const b64 = encodeBase64(bytes);
      entries.push(
        `  { path: ${jsString(path)}, contents: ${
          jsString(b64)
        }, encoding: "base64" },`,
      );
    } else {
      const contents = await Deno.readTextFile(url);
      entries.push(
        `  { path: ${jsString(path)}, contents: ${jsString(contents)} },`,
      );
    }
  }
  return `// GENERATED by scripts/gen-templates.ts — do not edit.
// Edit the real files under templates/ and run \`deno task gen\`.

const CORE_VERSION = "^0.2.0";

interface TemplateFile {
  path: string;
  // base64 for encoding "base64" (decoded to bytes on write), else file text.
  contents: string;
  encoding?: "base64";
}

const FILES: TemplateFile[] = [
${entries.join("\n")}
];

/** All files for a fresh app, with {{CORE}}/{{NAME}} substituted in text. */
export function templateFiles(projectName: string): TemplateFile[] {
  const sub = (s: string) =>
    s.replaceAll("{{CORE}}", CORE_VERSION).replaceAll("{{NAME}}", projectName);
  return FILES.map((f) =>
    f.encoding === "base64" ? f : { ...f, contents: sub(f.contents) }
  );
}
`;
}

async function fmt(source: string): Promise<string> {
  // Pipe through deno fmt so templates.gen.ts passes `deno fmt --check` in CI.
  const cmd = new Deno.Command("deno", {
    args: ["fmt", "-", "--ext", "ts"],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  });
  const child = cmd.spawn();
  const w = child.stdin.getWriter();
  await w.write(new TextEncoder().encode(source));
  await w.close();
  const { success, stdout, stderr } = await child.output();
  if (!success) {
    throw new Error(`deno fmt failed:\n${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout);
}

const check = Deno.args.includes("--check");
await assertManifestCovers();
const generated = await fmt(await render());

if (check) {
  let current = "";
  try {
    current = await Deno.readTextFile(OUT);
  } catch { /* missing = stale */ }
  if (current !== generated) {
    console.error(
      "templates.gen.ts is stale. Run `deno task gen` and commit the result.",
    );
    Deno.exit(1);
  }
  console.log("templates.gen.ts is up to date.");
} else {
  await Deno.writeTextFile(OUT, generated);
  console.log(`wrote ${OUT.pathname}`);
}
