// Inlines init/templates/ into committed templates.gen.ts so the published
// scaffolder reads nothing at runtime — no fetch of JSR package data files (the
// Fresh scaffolder makes the same embed-not-fetch choice). Run via deno task gen.

const HERE = new URL("../", import.meta.url);
const TEMPLATES = new URL("templates/", HERE);
const OUT = new URL("templates.gen.ts", HERE);

// [source, outputPath]. Source names diverge from output where a literal name
// breaks tooling: `gitignore` avoids a real dotfile; `deno.json` stays literal
// but is unpublished so Deno never loads it as a config for this dir.
const MANIFEST: ReadonlyArray<readonly [string, string]> = [
  ["deno.json", "deno.json"],
  ["vite.config.ts", "vite.config.ts"],
  ["server.prod.ts", "server.prod.ts"],
  ["gitignore", ".gitignore"],
  ["README.md", "README.md"],
  ["public/favicon.svg", "public/favicon.svg"],
  ["app/server.ts", "app/server.ts"],
  ["app/chevalier-islands.d.ts", "app/chevalier-islands.d.ts"],
  ["app/chevalier-manifest.d.ts", "app/chevalier-manifest.d.ts"],
  ["app/routes/_layout.tsx", "app/routes/_layout.tsx"],
  ["app/routes/_404.tsx", "app/routes/_404.tsx"],
  ["app/routes/_error.tsx", "app/routes/_error.tsx"],
  ["app/routes/index.tsx", "app/routes/index.tsx"],
  ["app/routes/about.tsx", "app/routes/about.tsx"],
  ["app/routes/hello/[name].tsx", "app/routes/hello/[name].tsx"],
  ["app/routes/api.ts", "app/routes/api.ts"],
  ["app/islands/counter.tsx", "app/islands/counter.tsx"],
  ["app/islands/quote.tsx", "app/islands/quote.tsx"],
];

// JSON.stringify escapes any bytes (backticks, ${}, backslashes) — no
// hand-managed template escapes, which is what the old inline templates.ts had.
function jsString(s: string): string {
  return JSON.stringify(s);
}

async function render(): Promise<string> {
  const entries: string[] = [];
  for (const [source, path] of MANIFEST) {
    const contents = await Deno.readTextFile(new URL(source, TEMPLATES));
    entries.push(
      `  { path: ${jsString(path)}, contents: ${jsString(contents)} },`,
    );
  }
  return `// GENERATED by scripts/gen-templates.ts — do not edit.
// Edit the real files under templates/ and run \`deno task gen\`.

export const CORE_VERSION = "^0.0.5";

export interface TemplateFile {
  path: string;
  contents: string;
}

const FILES: TemplateFile[] = [
${entries.join("\n")}
];

/** All files for a fresh app, with {{CORE}}/{{NAME}} substituted. */
export function templateFiles(projectName: string): TemplateFile[] {
  const sub = (s: string) =>
    s.replaceAll("{{CORE}}", CORE_VERSION).replaceAll("{{NAME}}", projectName);
  return FILES.map((f) => ({ path: f.path, contents: sub(f.contents) }));
}
`;
}

async function fmt(source: string): Promise<string> {
  // Pipe through deno fmt so templates.gen.ts passes `deno fmt --check` in CI.
  const cmd = new Deno.Command("deno", {
    args: ["fmt", "-", "--ext", "ts"],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  });
  const child = cmd.spawn();
  const w = child.stdin.getWriter();
  await w.write(new TextEncoder().encode(source));
  await w.close();
  const { success, stdout, stderr } = await child.output();
  if (!success) {
    throw new Error(`deno fmt failed:\n${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout);
}

const check = Deno.args.includes("--check");
const generated = await fmt(await render());

if (check) {
  let current = "";
  try {
    current = await Deno.readTextFile(OUT);
  } catch { /* missing = stale */ }
  if (current !== generated) {
    console.error(
      "templates.gen.ts is stale. Run `deno task gen` and commit the result.",
    );
    Deno.exit(1);
  }
  console.log("templates.gen.ts is up to date.");
} else {
  await Deno.writeTextFile(OUT, generated);
  console.log(`wrote ${OUT.pathname}`);
}
